---
title: "Ocean Conservancy, Urban Ocean Marine Debris Prediction"
subtitle: "Yinan Li, Tiffany Luo, Xiaofan Liu， Trevor Kapuvari"
author: "University of Pennsylvania"
date: "2024-05-07"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: "hide"
    theme: flatly
    highlight: tango
    number_sections: yes
mainfont: DejaVu Sans
editor_options: 
  markdown: 
    wrap: 72
---

# Praparing
```{r, warning=FALSE, message=FALSE, error=FALSE, include=FALSE,  }
knitr::opts_chunk$set(echo = TRUE)
#install.packages("bigrquery")
#install.packages("googleCloudStorageR")

library(bigrquery) # used for querying BigQuery
library(googleCloudStorageR)  # This library helps in interacting with GCS
library(tidyverse)
library(sf)
library(RSocrata)
library(viridis)
library(spatstat)
library(raster)
library(spdep)
library(FNN)
library(grid)
library(gridExtra)
library(knitr)
library(kableExtra)
library(osmdata)
library(tidycensus)
library(classInt)
library(RCurl)
library(httr)
library(osmdata)
library(randomForest)

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
st_c    <- st_coordinates
st_coid <- st_centroid
```

```{r, warning=FALSE, message=FALSE, error=FALSE,  }
# Set your GCS bucket
BUCKET_NAME <- "musa509_marine_pollution_prepared_data"

gcs_global_bucket(BUCKET_NAME)
```

```{r function_build, results='hide', message=FALSE, error=FALSE,  }
countfishnet <- function(fishnet,dataset){
  net <- 
  dplyr::select(dataset) %>% 
  mutate(count = 1) %>% 
  aggregate(., fishnet, sum) %>%
  mutate(count = replace_na(count, 0),
         uniqueID = 1:n(),
         cvID = sample(round(nrow(fishnet) / 24), 
                       size=nrow(fishnet), replace = TRUE))
  return(net)
}

knnfishnet <- function(fishnet,dataset,knum){
  vars_net <- dataset%>%
    st_join(fishnet, join=st_within) %>%
    st_drop_geometry() %>%
    group_by(uniqueID,osm_id) %>%
    summarize(count = n()) %>%
    left_join(fishnet, ., by = "uniqueID") %>%
    spread(osm_id, count, fill=0) %>%
    dplyr::select(-`<NA>`) %>%
    ungroup()
  vars_net <- vars_net %>%
    mutate(item.nn = nn_function(st_c(st_coid(vars_net)), 
                                           st_c(dataset),
                                           k = knum))
  return(vars_net)
}

visual <- function(net_one,point_one,variable_name){
grid.arrange(
  ggplot() +
  geom_sf(data = net_one, aes(fill = count), color = NA) +
  scale_fill_viridis() +
  labs(title = paste(variable_name,"count for the fishnet")) +
  mapTheme(),
  ggplot() + 
  geom_sf(data = chen_bdry) +
  geom_sf(data = point_one, colour="red", size=0.2, show.legend = "point") +
  labs(title= paste(variable_name,", Chennai")) +
  mapTheme(title_size = 14),
  nrow = 1
)
}
```

# 1. Querying Data from BigQuery
## 1.1. Prepare the BigQuery query
```{r load_litter, warning=FALSE, message=FALSE, error=FALSE,  }
# Load litter data
PROJECT_ID <- "musa509-marine-pollution"

# Authenticate
bq_auth(path = "https://raw.githubusercontent.com/YinanLi-15/MUSA509_Marine_Pollution/main/Feature_Engineering/keys/musa509-marine-pollution-4ad4b3458a23.json")

# Define your dataset and table
dataset_id <- "pollution"
table_id <- "litter"

# Construct your SQL query
sql <- sprintf("SELECT * FROM `%s.%s.%s`", PROJECT_ID, dataset_id, table_id)

# Specify the location if necessary
location <- "us-east1"  # Adjust this to match your table's location

# Execute the query with the location parameter
query_job <- bq_project_query(PROJECT_ID, sql, location = location)

# Download the query results into a dataframe
litter_df <- bq_table_download(query_job)

# View the first few rows of the dataframe
head(litter_df)

```

```{r litter_engineering, warning=FALSE, message=FALSE, error=FALSE,  }
litter_p <- litter_df%>%
  filter(master_material == 'PLASTIC')%>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326, agr = "constant")%>%
  st_transform('EPSG:32643')
```

```{r load_boundary, warning=FALSE, message=FALSE,  }
boundary <- st_read("https://raw.githubusercontent.com/YinanLi-15/MUSA509_Marine_Pollution/main/Data_Loading/functions/boundary.geojson")

boundary <- st_set_crs(boundary, 4326)%>%
  st_transform('EPSG:32643')
```

```{r fishnet_litter_people, message=FALSE, warning=FALSE, results='hide',  }
fishnet <- 
  st_make_grid(boundary,
               cellsize = 500, 
               square = TRUE) %>%
  .[boundary] %>%          
  st_sf() %>%
  mutate(uniqueID = 1:n())

litter_people <- litter_p%>%
  group_by(username)%>%
  tally()
```

```{r, warning=FALSE, message=FALSE,  }
litter_net <- 
  dplyr::select(litter_p) %>% 
  mutate(countlitter = 1) %>% 
  aggregate(., fishnet, sum) %>%
  mutate(countlitter = replace_na(countlitter, 0),
         uniqueID = 1:n(),
         cvID = sample(round(nrow(fishnet) / 24), 
                       size=nrow(fishnet), replace = TRUE))
```

```{r, message=FALSE, warning=FALSE, results='hide',  }
# reference: https://wiki.openstreetmap.org/wiki/Map_features#Entertainment,_Arts_&_Culture
amenity_wm <- c('waste_basket','waste_disposal','waste_transfer_station','recycling')
water<- c('canal','drain','ditch')
leisure <- c('park')
landuse <- c('commercial','residential','retail')
highway <- c('motorway','trunk','primary','secondary','tertiary','unclassified','residential')
act <- c('maxspeed')
amenity_food <- c('restaurant','pub','bar')

building <- ('apartments,')
```

```{r, message=FALSE, warning=FALSE, results='hide',  }
india <- getbb(place_name = "india", format_out = "polygon")
bb_df <- getbb(place_name = "chennai india", format_out = "data.frame")
bdry <- bb_df$boundingbox
chen_bd <- c(80.4301860, 13.2436939, 80.1101860, 12.8236939)
```

```{r, message=FALSE, warning=FALSE, results='hide',  }
bb_mb <- getbb(place_name = "mumbai india", format_out = "data.frame")
```

```{r transportation, message=FALSE, warning=FALSE, results='hide'}
trans <- opq(bbox = chen_bd) %>%
    add_osm_feature(key = 'highway', value = 'residential')%>%
  osmdata_sf()

trans_point <- bind_rows(
  pluck(trans,'osm_points'),
  st_centroid(pluck(trans,'osm_lines')))%>%
  dplyr::select(osm_id,geometry)%>%
  st_transform('EPSG:32643')%>%
  mutate(legend = 'road')

road_net <- countfishnet(fishnet,trans_point)
vars_net <- knnfishnet(fishnet,trans_point,3)

```

```{r, warning=FALSE, message=FALSE}
litter_no <- st_drop_geometry(litter_net)%>%dplyr::select(countlitter, uniqueID)
corr_trans_net <- road_net %>%
  left_join(litter_no, by = "uniqueID")

```


```{r restaurant data, warning=FALSE, message=FALSE}
restrt <- opq(bbox = chen_bd) %>%
    add_osm_feature(key = 'amenity', value = c('restaurant','pub','bar'))%>%
  osmdata_sf()

restrt_point <- pluck(restrt,'osm_points')%>%
  dplyr::select(osm_id,geometry)%>%
  st_transform('EPSG:32643')%>%
  mutate(legend = 'restaurant')

rstrt_net <- countfishnet(fishnet,restrt_point)

```

```{r corr-rest-litter, warning=FALSE, message=FALSE}
corr_net <- rstrt_net %>%
  left_join(litter_no, by = "uniqueID")
```



```{r, warning=FALSE, message=FALSE, results='hide'}
vars_net_rstrt <- knnfishnet(fishnet,restrt_point,3)

vars_net_rstrt.long.nn <- 
  dplyr::select(vars_net_rstrt, ends_with(".nn")) %>%
    gather(Variable, value, -geometry)
```

```{r water data, warning=FALSE, message=FALSE}
chen_water <- opq(bbox = chen_bd) %>%
    add_osm_feature(key = 'water', value = water)%>%
  osmdata_sf()

chen_water_point <- pluck(chen_water,'osm_points')%>%
  dplyr::select(osm_id,geometry)%>%
  st_transform('EPSG:32643')%>%
  mutate(legend = 'water')

water_net <- countfishnet(fishnet,chen_water_point)

```

```{r water visualization, warning=FALSE}
corr_water_net <- water_net %>%
  left_join(litter_no, by = "uniqueID")
print(chisq.test(corr_water_net$count,corr_water_net$countlitter))
```

```{r, warning=FALSE, message=FALSE}
vars_net_water <- knnfishnet(fishnet,chen_water_point,3)

vars_net_water.long.nn <- 
  dplyr::select(vars_net_water, ends_with(".nn")) %>%
    gather(Variable, value, -geometry)
```


```{r waste data, warning=FALSE, message=FALSE}
chen_waste <- opq(bbox = chen_bd) %>%
    add_osm_feature(key = 'amenity', value = amenity_wm)%>%
  osmdata_sf()

chen_waste_point <- pluck(chen_waste,'osm_points')%>%
  dplyr::select(osm_id,geometry)%>%
  st_transform('EPSG:32643')

waste_net <- countfishnet(fishnet,chen_waste_point)
```

```{r waste visualization, warning=FALSE, message=FALSE}
corr_waste_net <- waste_net %>%
  left_join(litter_no, by = "uniqueID")
print(chisq.test(corr_waste_net$count,corr_waste_net$countlitter))
```


```{r, warning=FALSE, message=FALSE}
vars_net_waste <- knnfishnet(fishnet,chen_waste_point,3)

vars_net_waste1.long.nn <- 
  dplyr::select(vars_net_waste, ends_with(".nn")) %>%
    gather(Variable, value, -geometry)

```

```{r, warning=FALSE, message=FALSE, results='hide'}
vars_net_rstrt <- knnfishnet(fishnet,restrt_point,3)
final_net <-
  left_join(litter_net, st_drop_geometry(vars_net_rstrt), by="uniqueID") 
```

```{r, warning=FALSE, message=FALSE}
final_net.nb <- poly2nb(as_Spatial(final_net), queen=TRUE)
final_net.weights <- nb2listw(final_net.nb, style="W", zero.policy=TRUE)
```


```{r, warning=FALSE, message=FALSE, results='hide'}
## see ?localmoran
local_morans <- localmoran(final_net$item.nn, final_net.weights, zero.policy=TRUE) %>% 
  as.data.frame()

# join local Moran's I results to fishnet
final_net.localMorans <- 
  cbind(local_morans, as.data.frame(final_net)) %>% 
  st_sf() %>%
  dplyr::select(Litter_Count = countlitter, 
                Local_Morans_I = Ii, 
                P_Value = `Pr(z != E(Ii))`) %>%
  mutate(Significant_Hotspots = ifelse(P_Value <= 0.001, 1, 0)) %>%
  gather(Variable, Value, -geometry)
```

```{r, warning=FALSE, message=FALSE}
vars <- unique(final_net.localMorans$Variable)
varList <- list()
```

```{r, warning=FALSE, message=FALSE, results='hide'}
final_net <- final_net %>% 
  mutate(restaurant.isSig = 
           ifelse(local_morans[,5] <= 0.001, 1, 0)) %>%
  mutate(restaurant.isSig.dist = 
           nn_function(st_c(st_coid(final_net)),
                       st_c(st_coid(filter(final_net, 
                                           restaurant.isSig == 1))), 
                       k = 1))
```

```{r, warning=FALSE, message=FALSE}
weight_net <- 
  left_join(litter_net, st_drop_geometry(road_net), by="uniqueID") 
weight_net <- weight_net %>% rename(countroad = count) %>% dplyr::select(!starts_with('cv'))

weight_net <- 
  left_join(weight_net, st_drop_geometry(water_net), by="uniqueID") 
weight_net <- weight_net %>% rename(countwater = count) %>% dplyr::select(!starts_with('cv'))

weight_net <- 
  left_join(weight_net, st_drop_geometry(rstrt_net), by="uniqueID") 
weight_net <- weight_net %>% rename(countrstrt = count) %>% dplyr::select(!starts_with('cv'))
```


```{r function trial, warning=FALSE, message=FALSE}
knnfishnet_new <- function(fishnet,dataset,knum){
  vars_net <- dataset%>%
    st_join(fishnet, join=st_within) %>%
    st_drop_geometry() %>%
    group_by(uniqueID,legend) %>%
    summarize(count = n()) %>%
    left_join(fishnet, ., by = "uniqueID") %>%
    spread(legend, count, fill=0) %>%
    dplyr::select(-`<NA>`) %>%
    ungroup()
  vars_net <- vars_net %>%
    mutate(item.nn = nn_function(st_c(st_coid(vars_net)), 
                                           st_c(dataset),
                                           k = knum))
  return(vars_net)
}

rest_net_temp <- knnfishnet_new(fishnet,restrt_point,3)
tran_net_temp <- knnfishnet_new(fishnet,trans_point,3)
water_net_temp <- knnfishnet_new(fishnet,chen_water_point,3)
```



```{r, warning=FALSE, message=FALSE}
rest_net_temp.long.nn <- 
  dplyr::select(rest_net_temp, ends_with(".nn")) %>%
    gather(Variable, value, -geometry)

tran_net_temp.long.nn <- 
  dplyr::select(tran_net_temp, ends_with(".nn")) %>%
    gather(Variable, value, -geometry)

water_net_temp.long.nn <- 
  dplyr::select(water_net_temp, ends_with(".nn")) %>%
    gather(Variable, value, -geometry)


```

```{r, warning=FALSE, message=FALSE, results='hide'}
final_net <-
  left_join(litter_net, st_drop_geometry(rest_net_temp), by="uniqueID")

final_net <-
  left_join(final_net, st_drop_geometry(tran_net_temp), by="uniqueID")

final_net <-
  left_join(final_net, st_drop_geometry(water_net_temp), by="uniqueID")%>%
  rename(rst_nn = item.nn.x,
         road_nn = item.nn.y,
         wtr_nn = item.nn)
```

```{r, warning=FALSE, message=FALSE, results='hide',  }
final_net.nb <- poly2nb(as_Spatial(final_net), queen=TRUE)
## ... and neighborhoods to list of weights
final_net.weights <- nb2listw(final_net.nb, style="W", zero.policy=TRUE)
```

```{r, warning=FALSE, message=FALSE}
local_morans_rst <- localmoran(final_net$restaurant, final_net.weights, zero.policy=TRUE) %>% 
  as.data.frame()
local_morans_road <- localmoran(final_net$road, final_net.weights, zero.policy=TRUE) %>% 
  as.data.frame()
local_morans_wtr <- localmoran(final_net$water, final_net.weights, zero.policy=TRUE) %>% 
  as.data.frame()
```

```{r, warning=FALSE, message=FALSE, results='hide'}
final_net.localMorans <- 
  cbind(local_morans_wtr, as.data.frame(final_net)) %>% 
  st_sf() %>%
  dplyr::select(rest_count = restaurant, 
                Local_Morans_I = Ii, 
                P_Value = `Pr(z != E(Ii))`) %>%
  mutate(Significant_Hotspots = ifelse(P_Value <= 0.001, 1, 0)) %>%
  gather(Variable, Value, -geometry)

vars <- unique(final_net.localMorans$Variable)
varList <- list()

```

```{r, warning=FALSE, message=FALSE, results='hide'}
final_net <- final_net %>% 
  mutate(rstrt.isSig = 
           ifelse(local_morans_rst[,5] <= 0.001, 1, 0)) %>%
  mutate(rstrt.isSig.dist = 
           nn_function(st_c(st_coid(final_net)),
                       st_c(st_coid(filter(final_net, 
                                           rstrt.isSig == 1))), 
                       k = 1))

final_net <- final_net %>%
  mutate(road.isSig = 
           ifelse(local_morans_road[,5] <= 0.001, 1, 0)) %>%
  mutate(road.isSig.dist = 
           nn_function(st_c(st_coid(final_net)),
                       st_c(st_coid(filter(final_net, 
                                           road.isSig == 1))), 
                       k = 1))

final_net <- final_net %>%
  mutate(wtr.isSig = 
           ifelse(local_morans_wtr[,5] <= 0.001, 1, 0)) %>%
  mutate(wtr.isSig.dist = 
           nn_function(st_c(st_coid(final_net)),
                       st_c(st_coid(filter(final_net, 
                                           wtr.isSig == 1))), 
                       k = 1))
```

```{r write_to_csv, warning=FALSE, message=FALSE, results='hide'}
# Write data frames to local CSV files, without headers or row names
dir.create(file.path('data'), showWarnings = FALSE)
write.table(final_net, "data/final_net.csv", 
   row.names = TRUE, col.names = TRUE, sep = ",")
```

```{r upload_gcs, warning=FALSE, message=FALSE}
# Upload CSV data to Google Cloud Storage by passing gsutil commands to system
gcs_url <- paste0("gs://", BUCKET_NAME, "/")
command <- paste("gsutil mb", gcs_url)
system(command)
gcs_data_dir <- paste0("gs://", BUCKET_NAME, "/final_net.csv")
command <- paste("gsutil cp data/final_net.csv", gcs_data_dir)
system(command)
command <- paste("gsutil ls -l", gcs_data_dir)
system(command, intern = TRUE)
```

```{r message=FALSE, warning=FALSE, results='hide'}
reg.ss.vars <- c("rst_nn", "rstrt.isSig.dist","road_nn", "road.isSig.dist","wtr_nn", "wtr.isSig.dist")

## RUN REGRESSIONS
reg.ss.spatialCV <- crossValidate(
  dataset = final_net,
  id = "uniqueID",
  dependentVariable = "countlitter",
  indVariables = reg.ss.vars) %>%
    dplyr::select(uniqueID, countlitter, Prediction, geometry)
```


```{r message=FALSE, warning=FALSE, results='hide'}
error_by_reg_and_fold <- 
  reg.ss.spatialCV %>%
    group_by(uniqueID) %>% 
    summarize(Mean_Error = mean(Prediction - countlitter, na.rm = T),
              MAE = mean(abs(Mean_Error), na.rm = T),
              SD_MAE = mean(abs(Mean_Error), na.rm = T)) %>%
  ungroup()



```

```{r, warning=FALSE, message=FALSE}
ml_breaks <- classIntervals(reg.ss.spatialCV$Prediction, 
                             n = 5, "fisher")
litter_risk_sf <-
  reg.ss.spatialCV %>%
  mutate(label = "Assessment Predictions",
         Risk_Category =classInt::findCols(ml_breaks),
         Risk_Category = case_when(
           Risk_Category == 5 ~ "5th",
           Risk_Category == 4 ~ "4th",
           Risk_Category == 3 ~ "3rd",
           Risk_Category == 2 ~ "2nd",
           Risk_Category == 1 ~ "1st")) %>%
  cbind(
    aggregate(
      dplyr::select(litter_p) %>% mutate(litterCount = 1), ., sum) %>%
      mutate(litterCount = replace_na(litterCount, 0))) %>%
  dplyr::select(label,Risk_Category, litterCount)
```

```{r, warning=FALSE, message=FALSE}
ggplot() +
    geom_sf(data = litter_risk_sf, aes(fill = Risk_Category), colour = NA) +
    scale_fill_viridis(discrete = TRUE) +
    mapTheme(title_size = 40)
```

